### ISSUE TITLE
Updating the avatar based on changes happened after initial loading

### ISSUE THREAD

**Issue by manumqln** [HaithemMosbahi/ngx-avatar#18] opened 2017-12-19 05:43 UTC
I could not get the avatar updated after some changes in the user data. For example, when I load the avatar initially there is no picture which makes it falls back to initials. Later, when a profile picture is added, I need to update the avatar with that image URL. This is not happening now. 

Could anyone please help me in getting this done?

Thanks in advance.

**Comment by manumqln** [comment] 2017-12-21 05:26
Could anyone please respond on this ? I am still stuck with this requirement.

**Comment by HaithemMosbahi** [comment] 2017-12-21 08:35
Hi,
Could you please share some code so I can reproduce your issue ? Actually, updating avatar data asynchronously is supported. You can check the demo folder, it has an example of getting user initials asynchronously after the first loading.

**Comment by manumqln** [comment] 2017-12-22 04:29
`<ngx-avatar [name]="userFullName" [src]="profilePic" size="24" textSizeRatio="2.5" initialsSize="2"></ngx-avatar>`
When the component loads initially there will not be any profile picture. So the initials will be displayed. But the user can upload a picture. I need it to reflect in the ngx-avatar in realtime without refreshing the screen by changing the variable `profilePic` and vice versa. This is not happening now.

Example:
[https://stackblitz.com/edit/ngx-avatar-demo-ttvfku](https://stackblitz.com/edit/ngx-avatar-demo-ttvfku)

See setting the image after the timeout in `app.component.ts`. But nothing happens.

**Comment by manumqln** [comment] 2017-12-22 09:11
Hope you got the issue now.

**Comment by manumqln** [comment] 2018-01-03 04:27
Is there any update on this issue?

**Comment by ArthurMauricioDelgadillo** [comment] 2018-01-30 17:08
Same problem here. But in a routing context. Where we reuse a template for show an organization or person avatar and behind its related organizations or people. So for example a company XYZ has 3 company partners (A, B and C). In our app we can see the avatar (logo) of the company XYZ and below its 3 partners, if we click to any of its partners we can see the same structure. But the problem happens when we click to a partner that doesn't have a logo image (for example C), 'cause of this amazing library we expected to get the initials of C, but that doesn't happen ...instead the same image of XYZ remains..
@manumqln  have you fix it? 

 Any updates? 
pd: sorry for my bad english :(

**Comment by manumqln** [comment] 2018-01-31 03:34
@ArthurMauricioDelgadillo I could not find a solution yet. Since the issue will impact badly in my project, I am not using this library for the time being.

**Comment by RobertThwaite** [comment] 2018-02-18 20:50
Here is a quick fix for you.

https://stackblitz.com/edit/ngx-avatar-demo-jqyda6

Simply wrapping module in a div and using a boolean to show and hide it. essentially refreshing the component.

Not nice.... but not a naughty fix.

**Comment by minuz** [comment] 2018-02-23 03:53
@manumqln,
You probably should use a service or a store to synchronize the state of the avatar.
From what I read from your issue, it seems like a sync issue that is not the library's responsibility.

I'm assuming you have the avatar in on one component and then the avatar is changed within a user profile, which is in a completely different component.

What I am doing is:
I created a singleton service (until I implement ngrx) provided within the app.module.
Both component inject the avatar service.
When the avatar is successfully uploaded to your application, the httpClient subscription triggers a BehaviorSubject with the new avatar value, which is subscribed on the topnav component (where I display the user avatar).
Due to this is structure, the component is able to properly react when a user change their avatar.
In case you are loading the avatar from Gravatar or Facebook or other external source, there's no way your application will be able to automatically react and therefore, you will need a manual refresh on the page to fetch that data.

I hope this can give you an idea on how to fix your problem...

I modified one snippet I have with a similar pattern to give you an idea of what I'm talking about.
Its not complete and its just to show a basic usage of the service that can be used to sync the state across different components throughout the app.

``` javascript
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
import { Injectable } from '@angular/core';

@Injectable()
export class AvatarStateSrevice {

    avatar$: BehaviorSubject<any>;

    constructor() {
        this.avatar$ = new BehaviorSubject(null);
    }

    getAvatar() {
        return this.avatar$.asObservable();
    }

    setAvatar(value: boolean) {
        this.avatar$.next(value);
    }
}
```

``` javascript
@Component({
    moduleId: module.id,
    selector: 'app-security',
    templateUrl: 'top.nav.component.html'
})
export class TopNavComponent implements OnInit {
    constructor(private avatarStateService: AvatarStateSrevice ) { }

    ngOnInit() {
        ....
        this.avatar$ = this.avatarStateService.getAvatar();
    }
}
```

``` html
<ngx-avatar src="{{avatar$ | async }}"></ngx-avatar>
```

Then on the upload component, let's say you have a onSuccess() method:
``` javascript
onSuccess(response){
     this.avatarStateService.setAvatar(response.newAvatar);
}
```

This should update the value on your top nav component with the new avatar.
Obviously you will need to modify to your structure but it should give you an idea...

I hope this helps...

**Comment by manumqln** [comment] 2018-02-23 05:24
@minuz Thanks for the well explained solution. I will check this and update.

**Comment by haivp3010** [comment] 2018-12-26 19:00
I think there is an issue with this line where it checks whether there is an existing source of the type before (in this case, it is "custom")
https://github.com/HaithemMosbahi/ngx-avatar/blob/44791e79942f6f05832536b669c56023460fad58/projects/ngx-avatar/src/lib/avatar.component.ts#L272

It is comparing the existing sourceType with an **toUppserCase** version while we can see that the enum definition is all lower case:
https://github.com/HaithemMosbahi/ngx-avatar/blob/44791e79942f6f05832536b669c56023460fad58/projects/ngx-avatar/src/lib/sources/avatar-source.enum.ts#L1-L12

I've made a pull request in case you want to merge it.

**Comment by haivp3010** [comment] 2018-12-27 04:49
@odahcam Thanks for your reviewing. I've applied your suggestions.

**Comment by HaithemMosbahi** [comment] 2019-01-01 15:49
@haivp3010 Thank you for your contribution and for your pull request. you are right we don't need the toUpperCase() there.
I have already started to write unit test to the component and do some refactoring in order to get rid of bugs like that. In the new version I already fixed that.

https://github.com/HaithemMosbahi/ngx-avatar/blob/a5cb9ea21215e50ac1a9a741e4f71a5a4c8ce23c/projects/ngx-avatar/src/lib/avatar.component.ts#L288 

I will do my best to get this merged as soon as possible.

**Comment by mhosman** [comment] 2019-02-21 22:51
I'm not able to change the value of src in the production build. There is any fix for this? My idea is to change one picture to another.

**Comment by odahcam** [comment] 2019-02-22 00:40
I don't know about this error, but as a workaround you can use multiple instances of `ngx-avatar` and switch them.

**Comment by mhosman** [comment] 2019-02-25 21:03
Hey @odahcam it could be great to fix this. Add several instances of ngx-avatar is not a good solution. The image should be updated after changing a src for another one.

**Comment by mhosman** [comment] 2019-03-12 17:41
Any news???

**Comment by odahcam** [comment] 2019-03-12 22:42
Sorry, I'm pretty busy at the moment, but I still can happily review some PR if someone wants to send one.

**Comment by sunithzysk** [comment] 2019-06-06 17:35
<ngx-avatar
        [src]="''" 
        [name]="username | async" 
        size="40" initialsSize="2"></ngx-avatar>

Where username is observable. Worked for me

**Comment by mhosman** [comment] 2019-06-10 18:10
This issue is already fixed.

**Comment by HaithemMosbahi** [comment] 2019-06-12 08:48
I will close this for now, feel free to create a new issue if you still have any problem with the component.

**Closed by HaithemMosbahi** 2019-06-12 08:48 UTC
