### ISSUE TITLE
HttpClientModule imported in AvatarModule override HttpClient defined in the AppModule

### ISSUE THREAD

**Issue by datencia** [HaithemMosbahi/ngx-avatar#58] opened 2019-04-02 12:00 UTC
Hi @HaithemMosbahi 

First, thank u for this library, good job. It's saving me a lot of time.

I'm facing an issue, I will try to explain it. In my app (Ionic3/Angular5), I have injected the `HttpClientModule` in the root module, aka `AppModule`, with a few HTTP interceptors.

Then I have a feature module (lazy loaded) where I'm using `ngx-avatar`. It is working but the services I have in that module stop working after adding the `AvatarModule`. They are not using the HTTP interceptors anymore.

I've forked your repo and seems it's because the `AvatarModule` is importing also the `HttpClientModule` so there are 2 instances in the angular dependency injection system and the feature module is using the one provided by the `AvatarModule`.

I have a patch removing the import for the `HttpClientModule` in the `AvatarModule` and everything works again. I can send a PR if you agree.

thx

**Comment by odahcam** [comment] 2019-04-02 16:37
Right, so the problem is that the library does not allows you to inject your app's HttpClient into the component. Well, here we have a situational case, because I don't know if it should really accept the user's app HttpClientModule or keep its own "safe" configured module. 🤔

**Comment by datencia** [comment] 2019-04-06 11:33
Okay, thanks. In the meantime, I'll keep using my patch.

**Comment by odahcam** [comment] 2019-04-06 14:25
Sure, I don't know what's the true intentions behind that implementation so I'll just ping @HaithemMosbahi .

**Comment by nickraphael** [comment] 2019-05-06 03:13
Oh man, I've lost a few days working out what was wrong in my app.  And this is it.  I use ngx-avatar in my lazy loaded modules and it's killing my http interceptors.  Any idea when this will be fixed?

**Comment by nickraphael** [comment] 2019-05-08 00:32
Is there an intention to fix this?  Any decent sized angular project will use http interceptors and almost all use lazy loading.  If this isn't fixed, then this library is kind of useless.  Which would be a real shame.  I'll give it a couple more days but I'll need to find a different library soon.

**Comment by odahcam** [comment] 2019-05-08 04:30
PRs are welcome. 🙂

**Comment by nickraphael** [comment] 2019-05-08 04:59
@odahcam I think there was a proposed fix mentioned above but wasn't accepted.  Last I heard we are waiting for feedback from @HaithemMosbahi.

**Comment by HaithemMosbahi** [comment] 2019-05-08 07:16
@nickraphael @datencia @odahcam Sorry for the late reply.
You are right, httpModule must be loaded only once in the application and therefore the library should not import it.
I will make a fix and release a new version today

**Comment by datencia** [comment] 2019-05-08 07:35
> @nickraphael @datencia @odahcam Sorry for the late reply.
> You are right, httpModule must be loaded only once in the application and therefore the library should not import it.
> I will make a fix and release a new version today

thx, I have a patch in my fork, I can send a PR if u agree.

**Closed** 2019-05-08 07:46 UTC

**Comment by HaithemMosbahi** [comment] 2019-05-08 10:15
I just published new version v3.4.0 that includes the fix.
