### ISSUE TITLE
Fallback to initials for missing image

### ISSUE THREAD

**Issue by gamefundas** [HaithemMosbahi/ngx-avatar#23] opened 2018-04-20 17:21 UTC
Is there a way to fallback to initials in case if the image is missing. In my use case we don't have pictures for all users so the component ends up with an error and missing image.

I can always write something as a precursor to check for existence of valid image prior to initializing ngx-avatar but think it would be better for the component itself to handle this.

Would like to know if this can be configured in any way.

Thanks
Andy

**Comment by rbenal** [comment] 2018-05-05 02:15
This is a good one, I have this problem too, there is a solution ?

**Comment by gamefundas** [comment] 2018-05-05 14:59
For now I couldn’t find a way to make the component work. As a work around I used *ngIf to switch between the picture and initials depending on the image being available or not.

**Comment by HaithemMosbahi** [comment] 2018-10-02 11:01
I think this is was caused by a bug related to the source priority. Could you please check if the problem is resolved with version 3.1.1.

This should work and fallback to initials : 
`<ngx-avatar src="broken-img-url" name="John Doe"></ngx-avatar>`

**Closed** 2018-10-02 11:09 UTC
Labels: enhancement
